# Generated by Django 3.2 on 2021-05-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20210526_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathway',
            old_name='CCMT_Date',
            new_name='CCMT_date',
        ),
    ]
