# Generated by Django 3.2 on 2021-05-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPAL', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='last_name',
            new_name='surname',
        ),
        migrations.AlterField(
            model_name='therapy',
            name='direct_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='indirect_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
