# Generated by Django 3.2 on 2021-05-11 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OPAL', '0002_auto_20210511_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='therapist',
            old_name='firstname',
            new_name='first_name',
        ),
    ]
